fs/rails-base

- lib/templates/slim/scaffold/edit.html.slim
- lib/templates/slim/scaffold/index.html.slim
- lib/templates/slim/scaffold/new.html.slim
- lib/templates/slim/scaffold/show.html.slim
This fixes 2 problems:
1. Because of old names of icon classes icons not visible
2. After scaffolding some templates '- title' causes errors and we must move this titles to i18n files? I think it's better to delete this from templates and add somehow to localization files.
> Old incorrect icons classnames changed to actual

- bin/setup
.bundle/confing stores `bundle install` options.
For example if we run once `bundle install --without development` next time
`bundle install` will be performed with saved option `--without development`.
> Remove .bundle/commit during bin/setup

- config/database.yml.example
You don't have to predefine credentials on `config/database.yml` since a freshly initialized system always contains one predefined user. This user will have the fixed ID 1, and by default (unless altered when running initdb) it will have the same name as the operating system user that initialized the database cluster.
So you should be able to log in into postgresql without passing any credentials info, either from console or from rails app.
```bash
psql -d postgres
```
> Drop username and password from config/database.yml

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- README.md
- bin/quality
- config/coffeelint.json
In addition to linting SCSS it'd be great to also lint CoffeeScript. While `coffeelint` is not good at detecting terribly awful code like:
```coffee
constructor: (@form, options) ->
do @init
init: =>
do @bind_events
bind_events: =>
@form.on 'submit', @submit
```
It will still help us to write _consistent_ CoffeeScript code. So, IMO, it worth adding to build process.
> Introduce Coffeelint

- CHANGELOG.md
- bin/quality
When we exclude 'config' dir from check only default config will be used
> Allow rails_best_practices gem to use config file at /config dir

- CHANGELOG.md
- config.ru
Related to: https://github.com/fs/rails-base/issues/299
> Require basic auth if ENV["AUTH_BASIC_PASS"] is set

- app/assets/javascripts/application.coffee
- app/assets/javascripts/current_user.coffee
- app/views/layouts/application.html.slim
Instead of relying on something visible only for authenticated user in DOM (which is ugly and fragile):
```coffee
if $('.current_user:first').size()
@sendRating(value)
```
we should hide implementation details and use global `currentUser` object. `currentUser` is set up from JSON data in application layout. With it example above would look like:
```coffee
if App.currentUser.isSignedIn()
@sendRating(value)
```
This PR also shows how to properly pass any global backend variables to client-side. For example, [flipper](https://github.com/jnunemaker/flipper) feature toggles could look like:
```slim
javascript:
App.currentUserData = #{raw current_user.to_json};
App.$flipper = #{raw js_feature_toggles };
```
```ruby
def js_feature_toggles
features_state = $flipper.features.map do |feature| …
```
> Introduce global `currentUser` object to JS environment

- CHANGELOG.md
- app.json
Heroku could create separate application per each pull request.
Environment variables and add-ons will be generated based on app.json.
https://devcenter.heroku.com/articles/github-integration#review-apps
> Add app.json to enable Heroku Review Apps

- .env.example
- CHANGELOG.md
- config.ru
- config/initializers/auth_basic.rb
- config/initializers/canonical_host.rb
Add initializers to configure middlewares:
* `config/initializers/canonical_host.rb` - `Rack::CanonicalHost`
* `config/initializers/auth_basic.rb` - `Rack::Auth::Basic`
> Move CanonicalHost and Auth::Basic configuration to initializers

- .env.example
- config/environments/production.rb
- config/initializers/assets.rb
* `ENV["ASSET_HOST"]`, ex.: http://d2oek0c5zwe48d.cloudfront.net
* `ENV["ASSETS_VERSION"]`, by default "1.0"
https://devcenter.heroku.com/articles/using-amazon-cloudfront-cdn#amazon-cloudfront
> Add ability to specify custom asset_host via ENV

- .env.example
- config/environments/production.rb
In development mode `config.action_controller.asset_host` could be skipped,
so no need to setup `ASSET_HOST` as `localhost:500`.
> Make ASSET_HOST optional

- lib/tasks/assets.rake
Extend the default assets:precompile by gzipping all assets once the default
Sprockets behavior has completed. This is needed because Sprockets 2.x does
not gzip static assets like SVGs, and Sprockets 3 no longer does gzipping at all!
https://github.com/rails/sprockets/issues/26
> Add gzipping for assets

- Gemfile
No need to require gem used only in `bin/quality` via CLI.
This saves some memory in development and test environments.
> Do not require quality gems

- CHANGELOG.md
- Gemfile
- Gemfile.lock
Due to UglifyJS vulnerability [uglifier](https://github.com/lautis/uglifier) should be updated.
Details: https://github.com/rubysec/ruby-advisory-db/pull/202
> Update Uglifier gem

- .env.example
- config/initializers/rollbar.rb
To be able to use Rollbar Heroku add-on out of the box `ROLLBAR_KEY`
renamed to `ROLLBAR_ACCESS_TOKEN`.
> Use ROLLBAR_ACCESS_TOKEN instead of ROLLBAR_KEY

- CHANGELOG.md
- Gemfile
- config/application.rb
- config/environments/production.rb
- config/initializers/mini_profiler.rb
Before Rack::MiniProfiler authorization step was performed in the
controller's before action. This commit moves it to initializer.
Also we disable MiniProfiler by default, it could be enabled with `pp=enable`
query string.
Bug in production environment fixed when MiniProfiler does not work with
Rack::Deflater.
https://github.com/MiniProfiler/rack-mini-profiler#custom-middleware-ordering-required-if-using-rackdeflate-with-rails
> Move Rack::MiniProfiler authorization to initializer

- Gemfile.lock
Nokogiri gem contains several vulnerabilities in libxml2 and libxslt
https://github.com/sparklemotion/nokogiri/issues/1374
> Upgrade nikogiri to close CVE-2015-1819

- CHANGELOG.md
- Introduce [Draper](https://github.com/drapergem/draper) for presenting models into views
- Move Rack::MiniProfiler authorization to initializers
- Add ability to configure SMTP Mailer options not only with SendGrid via `config/initializers/mailer.rb`
- [Remove `app_config`](https://github.com/fs/rails-base/pull/342) shortcut and use `ENV` exclusively
- Turning on Partial Double Verification for Rspec
- Replace [rails_12factor](https://github.com/heroku/rails_12factor) with [rails_stdout_logging](https://github.com/heroku/rails_stdout_logging)
- Update [foundation-rails gem](https://github.com/zurb/foundation-rails)
- Update [rollbar gem](https://github.com/rollbar/rollbar-gem)
- Add gem [rack-mini-profiler](https://github.com/MiniProfiler/rack-mini-profiler) for displaying speed badge …
> Release 1.7

- CHANGELOG.md
- app/views/application/_messages.html.slim
According documentation (http://foundation.zurb.com/sites/docs/v/5.5.3/components/alert_boxes.html), Foundation alerts "close" button needs to have an `href` attribute. Without `href` it's normally works on desktops and some mobile devices, but on iOs Safari it matters and alerts won't closing.
> Fix alerts dismiss button on iOs devices

- .rspec
Show slowest 10 specs (with path and consumed time)
Read more about [profile_examples](https://www.relishapp.com/rspec/rspec-core/docs/configuration/profile-examples) option
> Show slowest specs through "profile_examples" option

- app/decorators/application_decorator.rb
- app/policies/application_policy.rb
To make sure we support url helpers we need to delegate
`to_model` to original object.
In form we will use `user.to_model` manually while this PR not merged
https://github.com/plataformatec/simple_form/pull/1256
Also make sure we use original object in policy object.
> Make sure decorated models respond to `to_model`

- Gemfile.lock
when we try to use webmock we get next error:
```
require 'webmock/rspec'
NameError: uninitialized constant Syck
from /Users/artembiserov/src/open-source/rails-base/.bundle/ruby/2.2.0/gems/safe_yaml-1.0.1/lib/safe_yaml/syck_node_monkeypatch.rb:42:in `<top (required)>'
```
> update safe-yaml gem

- app/views/application/_footer.html.slim
As Timur said correct spelling will be Flatstack not FlatStack
> Fix misspelling of company name in footer

- .gitattributes
- CHANGELOG.md
Instead of leaving conflicts the union merge option will resolve conflicts favouring both side of the lines.
> Configure .gitattributes to avoid merge conflicts

- Gemfile.lock
update rspec-core to 3.4.5 to prevent next warning:
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
> Update rspec core to 3.4.4

- app/controllers/users/registrations_controller.rb
- app/sanitizers/user/parameter_sanitizer.rb
- app/views/users/registrations/edit.html.slim
- config/rails_best_practices.yml
- config/routes.rb
- spec/features/user/account/update_spec.rb
Suggestion is to skip password confirmation because this feature is a little bit non-obvious and sometimes even those users who knows about it forget to input current password before hitting the update button.
> Allow users to edit their account without providing a current password

- CHANGELOG.md
- Introduce [Rspec-Its](https://github.com/rspec/rspec-its)
- Configure `.gitattributes` to avoid merge conflicts due to `CHANGELOG`
- Upgrade rubocop to 0.39.0, rubocop-rspec to 1.4.1, active_link_to to 1.0.3, faker to 1.6.3, slim_lint to 0.7.2
> Release 1.9

- CHANGELOG.md
- spec/factories/users.rb
Issue: When `'` becomes `&#39;` on text comparisons:
```ruby
expected the body to contain "Jermain O'Keefe" but was "<p>Jermain O&#39;Keefe!</p>
```
Solution: using another `Faker`'s method, which generates string without special chars.
---
Discussed in this PR: https://github.com/fs/rails-base/pull/411
> Fix flaky specs based on encoded html entities

- CHANGELOG.md
- Gemfile.lock
Fix for [`nokogiri 1.6.7.2 CVE-2015-8806`](https://github.com/sparklemotion/nokogiri/issues/1473) issue (Denial of service or RCE from libxml2 and libxslt)
> Update nokogiri gem

- CHANGELOG.md
- Gemfile.lock
rack-mini-profiler may [disclose information to unauthorized users](https://github.com/MiniProfiler/rack-mini-profiler/commit/4273771d65f1a7411e3ef5843329308d0e2d257c)
Newest version (0.10.1) has fix for this.
> Upgrade rack-mini-profiler to 0.10.1

- CHANGELOG.md
- spec/mailers/previews/devise_mailer_preview.rb
Preview classes stored at `spec/mails/previews`
Preview will be available in http://lvh.me:5000/rails/mailers/user_mailer
Doc: http://guides.rubyonrails.org/action_mailer_basics.html#previewing-emails
> Email previews for `DeviseMailer` at http://lvh.me:5000/rails/mailers

- app/controllers/users/registrations_controller.rb
- spec/features/user/account/update_spec.rb
Fixes #463 
Actually `#update_without_password` does not allow to change password http://www.rubydoc.info/github/plataformatec/devise/Devise%2FModels%2FDatabaseAuthenticatable%3Aupdate_without_password
> Fix password updating

- lib/templates/rails/decorator/decorator.rb
In order to eliminate creation draper decorators with `delegate_all` and example of hot to use decorators i've rewritten the template.
> Override decorator template

- Gemfile.lock
Updating nokogiri to resolve security warnings when running `bin/ci`. Nokogiri 1.7.2 introduced two CVE fixes which 1.7.1 didn't contain. 
* [Nokogiri Changelog](https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.md#172--2017-05-09)
* [CVE-2017-5029](http://people.canonical.com/~ubuntu-security/cve/2017/CVE-2017-5029.html)
* [CVE-2016-4738](http://people.canonical.com/~ubuntu-security/cve/2016/CVE-2016-4738.html)
1. If necessary, run `bin/setup`
2. Run `bundle install` otherwise for this branch which `bin/setup` would also cover
3. Run `bin/ci`
4. Result should be no security warnings
> Update Nokogiri to >=1.7.2 for CVE issues

- Gemfile.lock
Right now we have 2.4.1 in Gemfile and 2.3.3 in Gemfile.lock
List of steps to manually test introduced functionality:
* Make sure application deployed to Heroku with ruby version 2.4.1
While reviewing pull-request (especially when it's your pull-request),
please make sure that:
- you understand what problem is solved by PR and how is it solved
- new tests are in place, no redundant tests
- DB schema changes reflect new migrations
- newly introduces DB fields have indexes and constraints
- routes are RESTful, no useless routes
- there are no missed files (migrations, view templates)
- required ENV variables added and described in `.env.example` and added to Heroku
- associated Heroku review app works correctly with introduced changes
Nope
> Make sure 2.4.1 specified in Gemfile.lock

- config/database.yml
This PR fixes application startup failure with error `comparison of Integer with String failed`  when `MAX_THREADS` or `DB_POOL` env variable is set
> Fix database.yml when MAX_THREADS or DB_POOL is set

- db/migrate/20100713113845_devise_create_users.rb
Hey guys,
This error appearing when you try to deploy Rails 5.1 application to Heroku:
https://github.com/RolifyCommunity/rolify/issues/444
@timurvafin please take a look
> Rails 5.1 / Heroku database migration bug fix

- Gemfile.lock
Update nokogiri to `1.8.2` to eliminate CVE-2017-15412
Update libv8 to `5.9.211.38.1` to stop breaking `bin/setup` (mini_racer needs it)
Run `bin/quality` and make sure that no vulnerabilities are found
While reviewing pull-request (especially when it's your pull-request),
please make sure that:
- you understand what problem is solved by PR and how is it solved
- new tests are in place, no redundant tests
- DB schema changes reflect new migrations
- newly introduces DB fields have indexes and constraints
- routes are RESTful, no useless routes
- there are no missed files (migrations, view templates)
- required ENV variables added and described in `.env.example` and added to Heroku
- associated Heroku review app works correctly with introduced changes
–
> Update nokogiri to 1.8.2 

- Gemfile.lock
Update rails-html-sanitizer gem to prevent vulnerability: [CVE-2018-3741](https://groups.google.com/forum/#!msg/rubyonrails-security/tP7W3kLc5u4/uDy2Br7xBgAJ)
Run `bin/quality`
> Update rails-html-sanitizer gem to 1.0.4

- CHANGELOG.md
- Gemfile.lock
Updated rack-mini-profiler gem because old version shows warning:
<Rack::MiniProfiler::MemoryStore::CacheCleanupThread:0x00007fbece793170@/Users/vladimir/src/rails-base/.bundle/ruby/2.5.0/bundler/gems/rack-mini-profiler-1b79f49f36df/lib/mini_profiler/storage/memory_store.rb:71 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
/Users/vladimir/src/rails-base/.bundle/ruby/2.5.0/bundler/gems/rack-mini-profiler-1b79f49f36df/lib/mini_profiler/storage/memory_store.rb:73:in `block in initialize_cleanup_thread': undefined method `sleepy_run' for #<Rack::MiniProfiler::MemoryStore:0x00007fbece793288> (NoMethodError)
> Updated rack-mini-profiler to prevent warning messages

- Gemfile
- Gemfile.lock
- spec/features/visitor/password_reset_spec.rb
- spec/features/visitor/resend_confirmation_email_spec.rb
- spec/features/visitor/sign_up_spec.rb
- spec/rails_helper.rb
- spec/support/capybara.rb
- spec/support/email.rb
https://github.com/fs/rails-base/issues/503
Replaced email_spec gem with capybara_email
> Replace email spec with capybara email

- spec/support/capybara.rb
https://github.com/fs/rails-base/issues/524
Disable animations for tests to prevent strange flaky tests
> Disable animations for tests to prevent strange flaky tests
