fs/rails-base

- app/views/devise/passwords/edit.html.slim
- app/views/devise/registrations/edit.html.slim
- app/views/devise/registrations/new.html.slim
- config/locales/helpers.en.yml
- config/locales/models/user.en.yml
> Translate buttons using i18n API

- Gemfile.lock
- spec/features/user/manage_account/update_account_spec.rb
Update formulaic gem to the latest version for new features, such a ```fill_form_and_submit``` for example.
> Update Formulaic gem

- spec/support/database_cleaner.rb
> Fix database-cleaner config

- CHANGELOG.md
- app/views/kaminari/_first_page.html.slim
- app/views/kaminari/_gap.html.slim
- app/views/kaminari/_last_page.html.slim
- app/views/kaminari/_next_page.html.slim
- app/views/kaminari/_page.html.slim
- app/views/kaminari/_paginator.html.slim
- app/views/kaminari/_prev_page.html.slim
- config/rails_best_practices.yml
Views downloaded directly from https://github.com/amatsuda/kaminari_themes using `bin/rails g kaminari:views foundation`
> Add views for kaminari to render pagination in style.

- CHANGELOG.md
- app/views/users/passwords/edit.html.slim
- app/views/users/registrations/edit.html.slim
- app/views/users/registrations/new.html.slim
- config/locales/helpers.en.yml
- config/locales/titles.en.yml
- spec/features/user/manage_account/update_account_spec.rb
See #287 for issue description.
/cc @timurvafin, @rustemginiyatullin
> Fix title on devise pages

- app/views/kaminari/_paginator.html.slim
Described in https://github.com/amatsuda/kaminari/issues/73
> Row html with slim template paginator view on production

- .env.example
- CHANGELOG.md
- Gemfile
- Gemfile.lock
- config.ru
Related to https://github.com/fs/rails-base/issues/298
> Add canonical host.

- .env.example
- CHANGELOG.md
- Gemfile
- Gemfile.lock
- README.md
- app/views/layouts/application.html.slim
- config/initializers/google_analytics.rb
> add Google Analytics

- Brewfile
- README.md
Graphviz used by rails-erd gem to generate entity-relationship diagram.
> Add graphviz to Brewfile

- app/views/application/_footer.html.slim
- app/views/pages/about.html.slim
- app/views/pages/home.html.slim
- app/views/pages/privacy.html.slim
- app/views/pages/terms.html.slim
- config/routes.rb
- spec/features/visitor/pages/about_spec.rb
- spec/features/visitor/pages/home_spec.rb
- spec/features/visitor/pages/privacy_spec.rb
- spec/features/visitor/pages/terms_spec.rb
Add example of marketing pages: Privacy, Terms, About.
> Examples: Add marketing pages

- .env.example
- app/controllers/application_controller.rb
- app/controllers/feedbacks_controller.rb
- app/mailers/application_mailer.rb
- app/models/feedback.rb
- app/views/application/_footer.html.slim
- app/views/application_mailer/feedback.html.slim
- app/views/application_mailer/feedback.text.erb
- app/views/feedbacks/new.html.slim
- config/application.rb
- config/locales/flash.en.yml
- config/routes.rb
- spec/factories/feedbacks.rb
- spec/features/visitor/create_feedback_spec.rb
Adds functionality to send feedback emails to address specified via `FEEDBACK_EMAIL` environment variable.
* `Feedback` - model for validation, could be connected with DB
* `FeedbacksController`
* `ApplicationMailer#feedback`
> Examples: Feedback form

- config/environments/production.rb
1. Adds cache headers for assets
2. Enables compression in staging and production for controller generated
responses.  It does not modify assets delivered through the asset pipeline, which ideally
we'd deliver via a CDN. - https://robots.thoughtbot.com/content-compression-with-rack-deflater
> Improve assets cache headers and add gzip compression for controller generated responses.

- Gemfile.lock
Since `config.serve_static_assets` has been renamed to `config.serve_static_files`
we need to update rails-12factor gem.
> Update rails-12factor gem

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- README.md
- config/rubocop.yml
> Introduce rubocop-rspec

- CHANGELOG.md
- Gemfile
- Gemfile.lock
Related to: https://github.com/fs/rails-base/issues/347
> [#347] Upgrade rollbar gem

- .env.example
- CHANGELOG.md
- Gemfile
- Gemfile.lock
Related to: https://github.com/fs/rails-base/issues/337
> Replace rails12 factor with rails stdout logging 337

- CHANGELOG.md
- spec/spec_helper.rb
Related to: https://github.com/fs/rails-base/issues/353
> [#353] Turning on partial double verification

- spec/spec_helper.rb
https://github.com/rspec/rspec-mocks/blob/master/features/old_syntax/README.md
https://github.com/rspec/rspec-expectations/blob/master/features/syntax_configuration.feature
> use <expect> for rspec-mocks

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- README.md
- app/controllers/concerns/authentication.rb
- app/decorators/application_decorator.rb
- app/decorators/user_decorator.rb
- app/helpers/application_helper.rb
- app/mailers/devise_mailer.rb
- app/mailers/user_mailer.rb
- app/models/user.rb
- app/views/devise_mailer/confirmation_instructions.html.slim
- app/views/devise_mailer/reset_password_instructions.html.slim
- app/views/user_mailer/confirmation_instructions.html.slim
- app/views/users/registrations/edit.html.slim
- config/initializers/devise.rb
- config/rails_best_practices.yml
- db/seeds/development/all.seeds.rb
After several attempts to use PORO for presentation layer I've ended up b/c of resulted things became too complicated. So let's try to use Draper carefully.
There is the only one rule: do not use `delegate_all` in decorators.
It's very important to control what methods are available on decorated
object in views to prevent Law of Demeter prohibition.
> Introduce Draper gem for presentation layer

- config/initializers/skim.rb
- config/initializers/slim.rb
Close https://github.com/fs/rails-base/issues/369
> Fixup Skim/Slim warnings

- app/views/layouts/application.html.slim
Related to: https://github.com/fs/rails-base/issues/363
> [#363] Escape json using slim

- config/application.rb
Old version was not setting `from` option properly.
> Fix ActionMailer default from

- config/initializers/filter_parameter_logging.rb
Filter out from log files Amazon S3 locations application is redirecting to.
Closes #394
> Filter redirects from logs

- CHANGELOG.md
- db/seeds/development/all.seeds.rb
- spec/factories/users.rb
- spec/features/user/account/cancel_spec.rb
- spec/features/user/account/update_spec.rb
- spec/features/user/sign_out_spec.rb
- spec/features/visitor/password_reset_spec.rb
- spec/features/visitor/resend_confirmation_email_spec.rb
- spec/features/visitor/sign_in_spec.rb
> User factory generate confirmed user by default

- app/controllers/application_controller.rb
> Respond to HTML by default

- app/decorators/application_decorator.rb
Decorated collections could be paginated with `paginate` helper in views.
New `PaginatingDecorator` delegates required methods to collection itself.
Closes #385
> Support Kaminari with Draper

- app/decorators/paginating_decorator.rb
PaginatingDecorator was introduced in from https://github.com/fs/rails-base/pull/397/files
> Add missing PaginatingDecorator

- spec/features/user/account/cancel_spec.rb
- spec/features/user/account/update_spec.rb
- spec/features/user/sign_out_spec.rb
- spec/support/features/shared_contexts/user_signed_in.rb
> Add rspec shared context for when current user signed in

- Gemfile
- Gemfile.lock
> Update skim to 0.10

- README.md
Closes https://github.com/fs/rails-base/issues/368
Reworked version of https://github.com/fs/rails-base/pull/417
> Removed 'depth' parameter recommendation, updated README and CHANGELOG

- CHANGELOG.md
- Gemfile
- Gemfile.lock
https://github.com/rspec/rspec-its
> Add rspec-its gem

- README.md
> Fix Semaphore badge

- Gemfile.lock
- app/views/layouts/application.html.slim
*Update Google Analytics to 1.1.1 version
*Make sure Google Analytics used only with GA_TRACKER env variable
List of steps to manually test introduced functionality:
* Go to Application
* Sign in
* ...
While reviewing pull-request (especially when it's your pull-request),
please make sure that:
- you understand what problem is solved by PR and how is it solved
- new tests are in place, no redundant tests
- DB schema changes reflect new migrations
- newly introduces DB fields have indexes and constraints
- routes are RESTful, no useless routes
- there are no missed files (migrations, view templates)
- required ENV variables added and described in `.env.example` and added to Heroku
- associated Heroku review app works correctly with introduced changes
Notes regarding deployment the …
> Make sure Google Analytics used only with GA_TRACKER env variable

- Gemfile.lock
Update loofah to `2.2.1` to eliminate [CVE-2018-8048](https://github.com/flavorjones/loofah/issues/144)
Run `bin/quality` and make sure that no vulnerabilities are found
While reviewing pull-request (especially when it's your pull-request),
please make sure that:
- you understand what problem is solved by PR and how is it solved
- new tests are in place, no redundant tests
- DB schema changes reflect new migrations
- newly introduces DB fields have indexes and constraints
- routes are RESTful, no useless routes
- there are no missed files (migrations, view templates)
- required ENV variables added and described in `.env.example` and added to Heroku
- associated Heroku review app works correctly with introduced changes
–
> Update loohaf to 2.2.1

- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- README.md
- config/initializers/generators.rb
- db/seeds/development/all.seeds.rb
- spec/factories/sequences.rb
- spec/factories/users.rb
- spec/support/factory_girl.rb
FactoryGirl upgraded to FactoryBot and factories refactored a little.
Removed Pry because we already have Byebug and it has more stars on Github)
> Updated FactoryBot gem

- Gemfile
- Gemfile.lock
- README.md
- package.json
- spec/features/user/account/cancel_spec.rb
- spec/features/user/sign_out_spec.rb
- spec/features/visitor/sign_in_spec.rb
- spec/rails_helper.rb
- spec/support/capybara.rb
- yarn.lock
- Removed Poltergeist
- Configured using capybara with chromedriver
- Downraged jQuery version to 2.x because of strage issue with Foundation (will update it again with founation-rails update)
> Removed Poltergeist; Added ChromeDriver

- .env.example
- config/application.rb
- spec/features/user/account/cancel_spec.rb
- spec/support/capybara.rb
Using HOST and PORT variables.
> Using HOST and PORT

- README.md
- bin/setup
https://github.com/fs/rails-base/issues/502
Update deps if running on macOS and brew installed. In other case (Linux OS) do nothing.
> Update deps via setup script

- .env.example
- config/initializers/devise.rb
- spec/features/visitor/sign_in_spec.rb
Sign in attempts count decrease to 5, moved to env config, added test for account lockings
> Lock count in ENV and test for locking account

- config/initializers/secure_headers.rb
> Little quality fix

- .rubocop.yml
> Excluded file that must be as is
